function PR_GDPR_Class(){var self=this;var $=pjQuery_1_12_4;self.messageContainer=false;self.passInput=false;self.listUrl=false;self.consentUrl=false;self.pageContentUrl=false;self.urls={};self.options={};self.setOptions=function(options){self.options=options;};self.setUrls=function(urls){for(var url in urls){if(urls.hasOwnProperty(url)){self.urls[url]=self.linkCacheCompatibility(urls[url]);}}};self.linkCacheCompatibility=function(url){return self.addTimestamp(self.fixProtocolCaching(url));};self.fixProtocolCaching=function(url){if(-1===url.indexOf(window.location.protocol)){return url.replace(/https?:/,window.location.protocol)}
return url;};self.addTimestamp=function(url){var timestamp=new Date().getTime();if(-1!==url.indexOf('?')){return url+'&tmpstmp='+timestamp;}else{var urlParamConnector=('/'!==url.slice(-1))?'/':'';return url+urlParamConnector+'tmpstmp/'+timestamp+'/';}};self.getUpdateListUrl=function(){if(!self.urls.updateList)console.error('Before get ulr, initialize list action url');return self.urls.updateList;};self.getConsentUrl=function(){if(!self.urls.consent)console.error('Before get ulr, initialize consent action url');return self.urls.consent;};self.getPageContentUrl=function(){if(!self.urls.pageContent)console.error('Before get ulr, initialize page action url');return self.urls.pageContent;};self.getLaterUrl=function(){if(!self.urls.later)console.error('Before get ulr, initialize later action url');return self.urls.later;};self.getAllowedCookieUrl=function(){if(!self.urls.allowedCookie)console.error('Before get ulr, initialize cookie action url');return self.urls.allowedCookie;};self.getConsentCookieUrl=function(){if(!self.urls.consentCookie)console.error('Before get ulr, initialize consent cookie action url');return self.urls.consentCookie;};self.getDeclineCookieUrl=function(){if(!self.urls.declineCookie)console.error('Before get ulr, initialize decline cookie action url');return self.urls.declineCookie;};self.showFancybox=function(content,checkboxId){$.fancybox({content:'<div class="prgdpr-cms-wrapper">'+content+'</div>',maxWidth:600,padding:25,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1">'+'<div class="fancybox-skin fancybox-prgdpr-skin">'+'<div class="fancybox-outer">'+'<div class="print-policy">'+'<a href="#" onclick="PR_GDPR.printDocument()">'+Translator.translate('Print')+'</a>'+'</div>'+'<div class="fancybox-inner prgdpr-fancybox-inner"></div>'+'</div>'+'<div class="fancybox-buttons prgdpr-buttons">'+'<button class="prgdpr-agree button">'+Translator.translate('Agree')+'</button>'+'</div>'+'</div>'+'</div>'}});$('.fancybox-wrap button.prgdpr-agree').on('click',function(event){checkPrgdprCheckbox(document.getElementById(checkboxId));$.fancybox.close();});};self.printDocument=function(){var element=document.querySelector('.fancybox-inner.prgdpr-fancybox-inner');if(element){return printElem(element);}
return false;};function printElem(elem){var myWindow=window.open('','PRINT','height=400,width=600');myWindow.document.write('<html><head><title>'+document.title+'</title>');myWindow.document.write('</head><body >');myWindow.document.write('<h1>'+document.title+'</h1>');myWindow.document.write(elem.innerHTML);myWindow.document.write('</body></html>');myWindow.document.close();myWindow.focus();myWindow.print();myWindow.close();return true;}
function checkPrgdprCheckbox(element){if(!element.checked)$(element).trigger('click');}
self.showFormFancybox=function(content,header,className){$.fancybox({content:content,maxWidth:600,padding:25,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1">'+'<div class="fancybox-skin fancybox-prgdpr-skin">'+'<div class="fancybox-header">'+"<h3>"+header+"</h3>"+'</div>'+'<div class="fancybox-outer">'+'<div class="fancybox-inner prgdpr-fancybox-inner '+className+'"></div>'+'</div>'+'</div>'+'</div>'}});$('.fancybox-wrap .back-link').on('click',function(event){$.fancybox.close();});$('.fancybox-wrap button[type="submit"]').on('click',function(event){if(className=="prgdpr-delete guest"){sendRequestForGuestDelete();}else{sendRequest();}
event.preventDefault();});self.messageContainer=$('.fancybox-wrap .prgdpr-message-container');self.passInput=$('.fancybox-wrap input[name="password"]');};self.guestExport=function(){sendRequestForGuest();};function showSuccessFancybox(){$.fancybox({content:'<div class="prgdpr-success-content">'+$('#prgdpr-success-content').html()+'</div>',maxWidth:600,minWidth:200,minHeigh:300,scrolling:'no',tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1"><div class="fancybox-skin"><div class="fancybox-outer"><div class="fancybox-inner"></div></div></div></div>'}});}
function sendRequest(){self.messageContainer.empty();var value=self.passInput.val();if(value){var action=$('.fancybox-wrap form')[0].action;$.post(action,{password:value},renderResponse);}}
function sendRequestForGuest(){var value=$('#prgdpr-export-guest input[name="password"]').val();if(value){var action=$('#prgdpr-export-guest form')[0].action;$.post(action,{token:value},renderResponse);}}
function sendRequestForGuestDelete(){var value=$('#prgdpr-delete-guest input[name="token"]').val();if(value){var action=$('#prgdpr-delete-guest form')[0].action;$.post(action,{token:value},renderResponse);}}
function renderResponse(data){var response=JSON.parse(data);if(response.redirect){window.location.reload();return;}
if(response.file){showSuccessFancybox();setTimeout(function(){pjQuery_1_12_4.fancybox.close();},5000);window.location.href=PRGDPR_DOWNLOAD_URL;}else if(response.error){renderError(response.error);self.passInput.val('');}else{showSuccessFancybox();setTimeout(function(){location.href=BASE_URL;},30000)}}
function renderError(message){var elem=document.createElement('div');elem.className='error-msg';elem.innerText=message;self.messageContainer.append(elem);}
self.showUpdates=function(){$.get(self.getUpdateListUrl(),function(data){var response=JSON.parse(data);if(!response)return;if(response.requireParams){if(response.updateParams){showRequirePopups(response.requireParams,showUpdatePopups,response.updateParams);}else{showRequirePopups(response.requireParams);}}else if(response.updateParams){showUpdatePopups(response.updateParams);}})};function showUpdatePopups(popupsParam){$.fancybox.close();var popupParam=popupsParam.shift();if(!popupParam){return;}
$.get(self.getPageContentUrl()+'page_id/'+popupParam.cmsPageId+'/',function(response){if(response){$.fancybox({content:'<div class="prgdpr-cms-wrapper">'+response+'</div>',maxWidth:500,maxHeight:300,padding:25,tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1">'+'<div class="fancybox-skin fancybox-prgdpr-skin">'+'<span class="fancybox-item fancybox-close prgdpr-action-later"></span>'+'<div class="fancybox-outer prgdpr-modal-cms margin">'+'<div class="fancybox-text">'+popupParam.popupContent+'</div>'+'<div class="print-policy">'+'<a href="#" onclick="PR_GDPR.printDocument()">'+Translator.translate('Print')+'</a>'+'</div>'+'<div class="fancybox-inner prgdpr-fancybox-inner prgdpr-fancybox-inner--cms" style="box-sizing:border-box"></div>'+'</div>'+'<div class="fancybox-buttons prgdpr-buttons">'+'<button class="prgdpr-later prgdpr-action-later button">'+Translator.translate('Remind me later')+'</button>'+'<button class="prgdpr-agree prgdpr-action-agree button">'+Translator.translate('I Agree')+'</button>'+'</div>'+'</div>'+'</div>'},helpers:{overlay:{closeClick:false}},closeBtn:false});$('.fancybox-wrap .prgdpr-action-agree').on('click',function(event){$.post(self.getConsentUrl(),{cms_page_id:popupParam.cmsPageId,version:popupParam.version},function(data){var response=JSON.parse(data);if(response.error){console.error(response.error);}});showUpdatePopups(popupsParam);});$('.fancybox-wrap .prgdpr-action-later').on('click',function(event){$.get(self.getLaterUrl());$.fancybox.close();});}});}
function showRequirePopups(popupsParam,callback,callbackParams){$.fancybox.close();var popupParam=popupsParam.shift();if(!popupParam){if(callback&&callbackParams){callback(callbackParams);}
return;}
if(popupParam.cmsPageId==='0'){showRequirePopup(popupParam.label,null,popupParam,popupsParam,callback,callbackParams);}else{$.get(self.getPageContentUrl()+'page_id/'+popupParam.cmsPageId+'/',function(response){showRequirePopup(null,response,popupParam,popupsParam,callback,callbackParams);});}}
function showRequirePopup(label,response,popupParam,popupsParam,callback,callbackParams){if(response||label){$.fancybox({content:'<div class="prgdpr-cms-wrapper">'+(response||label)+'</div>',maxWidth:500,minWidth:300,maxHeight:300,padding:25,wrapCSS:'width: auto;',tpl:{wrap:'<div class="fancybox-wrap" tabIndex="-1">'+'<div class="fancybox-skin fancybox-prgdpr-skin">'+'<div class="fancybox-outer margin">'+'<div class="print-policy">'+'<a href="#" onclick="PR_GDPR.printDocument()">'+Translator.translate('Print')+'</a>'+'</div>'+'<div class="fancybox-inner prgdpr-fancybox-inner prgdpr-fancybox-inner--cms"></div>'+'<div class="fancybox-buttons prgdpr-buttons">'+'<button class="prgdpr-agree prgdpr-action-agree button">'+Translator.translate('I Agree')+'</button>'+'</div>'+'</div>'+'</div>'+'</div>'},helpers:{overlay:{closeClick:false}},closeBtn:false});$('.fancybox-wrap button.prgdpr-action-agree').on('click',function(event){$.post(self.getConsentUrl(),{cms_page_id:popupParam.cmsPageId,version:popupParam.version,label:label},function(data){var response=JSON.parse(data);if(response.error){console.error(response.error);}});showRequirePopups(popupsParam,callback,callbackParams);});}}
self.showCookieNotice=function(url){$.get(url||self.getAllowedCookieUrl(),function(data){var response=JSON.parse(data);if(response.notAllowed){$('#notice-cookie-block').show();}});};self.hideCookieNotice=function(){$('#notice-cookie-block').hide();};self.logCookieConsent=function(callback,url){logCookie(callback,url||self.getConsentCookieUrl());};self.logCookieDecline=function(callback,url){logCookie(callback,url||self.getDeclineCookieUrl());};function logCookie(callback,url){$.get(url,function(data){var response=JSON.parse(data);if(response){callback(response);}});}
self.addRequireClassToLabel=function(id){$('label[for$='+id+']').addClass('required');};}
var PR_GDPR=new PR_GDPR_Class();pjQuery_1_12_4(document).ready(function($){$(document).on('click',function(event){var content='';var header='';var className='';if(event.target.classList.contains('pr-inpopup')&&$(event.target).closest('.checkout-agreements').length){event.preventDefault();var li=$(event.target).closest('li');content=$('.agreement-content',li).html();var checkoutCheckboxId=$('input',li).attr('id');PR_GDPR.showFancybox(content,checkoutCheckboxId);return true;}
if(event.target.classList.contains('pr-inpopup')){event.preventDefault();var container=$(event.target).closest('.prgdpr-checkbox-container');var checkboxId=$('input',container)[0].getAttribute('id');if($('.prgdpr-checkbox-content',container).length){PR_GDPR.showFancybox($('.prgdpr-checkbox-content',container).html(),checkboxId);}else{PR_GDPR.showFancybox($('label',container).html(),checkboxId);}
return true;}
if(event.target.classList.contains('form-pr-inpopup')){event.preventDefault();var deleteForm=$('#prgdpr-delete');if(deleteForm.length){content=deleteForm.html();header=deleteForm.attr('title');className=deleteForm.attr('class');}
var exportForm=$('#prgdpr-export');if(exportForm.length){content=exportForm.html();header=exportForm.attr('title');className=exportForm.attr('class');}
PR_GDPR.showFormFancybox(content,header,className);}
if(event.target.classList.contains('form-pr-inpopup-guest')){event.preventDefault();var guestExportForm=$('#prgdpr-export-guest');if(guestExportForm.length){PR_GDPR.guestExport();}
var guestDeleteForm=$('#prgdpr-delete-guest');if(guestDeleteForm.length){content=guestDeleteForm.html();header=guestDeleteForm.attr('title');className=guestDeleteForm.attr('class');PR_GDPR.showFormFancybox(content,header,className);}}});$('html').addClass('prgdpr');PR_GDPR.showCookieNotice();});